### ISSUE TITLE
To-Do 

### ISSUE THREAD

**Issue by 0xffset** [RolEYder/eMarker-dashboard#1]
## Issues & bugs 
- [ ] Bug when you try to update the image of one product. 🔴

## Security issues 
- [x] Add a new layer of security to avoid unauthorized API callings. 🔴 

## Desing & funcionality 
- [x] Set responsity desing. 🟠 
- [x] Dark theme.  🟢
  
**Priority labels**

- 🔴 very, very important.
- 🟠 medium importance, but needed. 
- 🟢  Low importance, but too needed.
